### ISSUE TITLE
[6-2장] Using filesort에서 인덱스를 사용하는 경우

### ISSUE THREAD

**Issue by yebink** [gazi-gazi/real-mysql#13]
> `p.312` Using Filesort는 ORDER BY 처리가 인덱스를 사용하지 못할 때만 사용된다고 했는데, 

질문 :
![image](https://user-images.githubusercontent.com/19922698/100523559-ab42e000-31f4-11eb-805a-b0aba6d71e5d.png)

인덱스를 사용해도 결과가 마찬가지네.
해당 인덱스로 정렬이 안 되어 있어서 그런가? 그럼 왜 인덱스지...

그리고 한 가지 더 궁금한 건 밑에서 3번째 줄에 `hire_date 칼럼에는`~ 이부분 `last_name`인데 오타 난 거겠지?

**Comment by KimSeongGyu1** [comment]
https://dba.stackexchange.com/questions/109078/why-index-is-not-used-with-order-by
요기 답변을 읽어보니

The problem is that the SQL engine can only use one index per table reference.(the one for your primary key)
라고 하는데
emp_no를 사용해야지만 using filesort가 일어나지 않는 것이 맞는듯.

직접 해본 결과 emp_no에서만 using filesort가 일어나지 않음
![image](https://user-images.githubusercontent.com/56247080/100542293-49ce5000-328c-11eb-89d8-d2d5962f9acf.png)

오타는 맞는듯

**Comment by yebink** [comment]
흠 그럼 위에서 말하는 인덱스라는게 결국 PK만을 의미하는건가?

**Comment by yebink** [comment]
```sql
explain
select * from employees
order by hire_date desc; #index 사용   ==> type: All, Extra: Using filesort
```

```sql
explain
select hire_date (또는 emp_no) from employees
order by hire_date desc; #index 사용   ==> type: All, Extra: Using Index(커버링 인덱스)
```

이렇게 hire_date 또는 emp_no로 찾으면 인덱스 테이블만으로 찾을 수 있다. (데이터 파일을 접근하지 않아도 된다)
그래서 Using Index가 출력된다.
