### ISSUE TITLE
[7-4-9장] 서브 쿼리의 실행 순서

### ISSUE THREAD

**Issue by giantim** [gazi-gazi/real-mysql#48]
> `p.476` FROM 절에 사용하는 서브쿼리는 상관 서브 쿼리 형태로 사용할 수 없다.

```mysql
SELECT *
FROM departments d,
  (SELECT * FROM dept_emp de WHERE de.dept_no=d.dept_no) x
WHERE d.dept_no=x.dept_no LIMIT 10;
```

질문 : 상관 서브 쿼리가 왜 FROM 절에서 사용되지 못하는지 설명부탁드려요! 쿼리의 실행 순서와 관계가 있는 건가요? :)

**Comment by toneyparky** [comment]
# [TL;DR](https://ko.wikipedia.org/wiki/TL;DR)

- `Outer 쿼리`를 평가(evaluate)하기 위해서는 FROM 절의 테이블이 필요합니다. 하지만 `FROM 절 안의 상관 서브 쿼리`는 `outer 쿼리`가 평가되기 전에는 평가될 수 없습니다.
- 서로 조건이 상충되기 때문에 상관 서브 쿼리가 FROM 절에서 사용되지 못합니다.
- 다만 몇몇 DBMS(PostgreSQL, ...)에서는 이를 허용해주기도 한다고 하네요.

### 참고

- `Outer 쿼리`
~~~SQL
SELECT *
FROM departments d,
  (SELECT * FROM dept_emp de WHERE de.dept_no=d.dept_no) x
WHERE d.dept_no=x.dept_no LIMIT 10;
~~~

- `FROM 절 안의 상관 서브 쿼리`
~~~ SQL
(SELECT * FROM dept_emp de WHERE de.dept_no=d.dept_no)
~~~




---

# 구체적인 답변 도출 과정

[MySQL 5.7 공식문서](https://dev.mysql.com/doc/refman/5.7/en/subquery-restrictions.html)를 보시면 아래와 같이 FROM절에는 상관 서브 쿼리를 사용할 수 없다고 명시되어 있습니다.
([8.0](https://dev.mysql.com/doc/refman/8.0/en/subquery-restrictions.html)도 비슷한 내용입니다)

> Subqueries in the FROM clause cannot be correlated subqueries. They are materialized in whole (evaluated to produce a result set) during query execution, so they cannot be evaluated per row of the outer query. 
...


해당 부분에 설명이 부실해서 검색을 많이많이 해봤습니다만 비슷한 내용으로만 적혀있고 왜 서브쿼리를 사용할 수 없는지 시원하게 알려주는 글은 찾지 못했네요. 그래도 찾은 내용을 아래에 적어보겠습니다.

[오라클 문서](https://docs.oracle.com/javadb/10.8.3.0/tuning/ctuntransform25857.html)
> Expression subqueries that are not correlated
A subquery can be materialized if it is a noncorrelated expression subquery. A correlated subquery is one that references columns in the outer query, and so **has to be evaluated for each row in the outer query.**

[마리아DB 문서](https://mariadb.com/kb/en/subquery-limitations/#correlated-subqueries)
> Correlated Subqueries
Subqueries in the FROM clause cannot be correlated subqueries. They cannot be evaluated for each row of the outer query **since they are evaluated to produce a result set during when the query is executed.**

문서에 따르면 서브쿼리는 쿼리가 실행되는 동안에 결과 셋을 만들도록 평가되기에 외부 쿼리의 각 행에 대해 평가될 수 없다고 합니다.
여전히 도움은 안되네요.

---

그래서 [위키](https://en.wikipedia.org/wiki/Correlated_subquery)를 조금 찾아봤습니다.
## Correlated subqueries in the FROM clause
It is generally meaningless to have a correlated subquery in the FROM clause **because the table in the FROM clause is needed to evaluate the outer query, but the correlated subquery in the FROM clause can't be evaluated before the outer query is evaluated**, causing a chicken-and-egg problem. Specifically, MariaDB lists this as a limitation in its documentation.

However, in some database systems, it is allowed to use correlated subqueries while joining in the FROM clause, referencing the tables listed before the join using a specified keyword, producing a number of rows in the correlated subquery and joining it to the table on the left. For example, in PostgreSQL, adding the keyword LATERAL before the right-hand subquery,[2] or in Microsoft SQL Server, using the keyword CROSS APPLY or OUTER APPLY instead of JOIN[3] achieves the effect.

드디어 핵심적인 이유가 나온듯합니다.
- outer 쿼리를 평가하기 위해서는 FROM 절의 테이블이 필요합니다. 하지만 FROM 절 안의 상관 서브 쿼리는 outer 쿼리가 평가되기 전에는 평가될 수 없습니다.
- 닭이 먼저냐 달걀이 먼저냐 문제와 비슷하다고 설명하네요. (조금은 다른 것 같지만 상충되는 두 가지 방식을 설명한다고 생각하죠)
- 추가적으로 몇몇 DBMS에서는 FROM 절에 상관 서브 쿼리가 있어도 처리를 잘 해주나봅니다. 이에 대해 더 알고 싶다면 해당 DBMS를 공부해보세용~

---

[IBM에서는 correlated subquery를 정의](https://www.ibm.com/support/knowledgecenter/SSGU8G_14.1.0/com.ibm.sqlt.doc/ids_sqt_181.htm)하기에 FROM 절에 있는 컬럼을 참조하지 않는 서브쿼리라고 아에 명시를 해두었네요.

해당 링크의 하단에도 correlated subquery가 FROM 절에 사용될 경우에 대한 오류 예시를 적어두었네요.

You cannot use a correlated subquery in the FROM clause, however, as the following invalid example illustrates:
~~~SQL
SELECT item_num, stock_num FROM items, 
   (SELECT stock_num FROM catalog 
       WHERE stock_num = items.item_num) AS vtab;
~~~
~~~shell
The subquery in this example fails with error -24138:
ALL COLUMN REFERENCES IN A TABLE EXPRESSION MUST REFER
TO TABLES IN THE FROM CLAUSE OF THE TABLE EXPRESSION.
~~~
The database server issues this error because the items.item_num column in the subquery also appears in the Projection clause of the outer query, but the FROM clause of the inner query specifies only the catalog table. The term table expression in the error message text refers to the set of column values or expressions that are returned by a subquery in the FROM clause, where only uncorrelated subqueries are valid.

![image](https://user-images.githubusercontent.com/37579660/104703691-0015c800-575b-11eb-8ef7-21e4d899f3c2.png)
이미지를 보아서도 알 수 있듯 목차에는 FROM 절에서의 Subqueries가 아에 없기도 하구요!

끝!

**Comment by jjj0611** [comment]
상관서브쿼리란 내부의 쿼리에서 외부 쿼리의 테이블의 데이터를 참조하는 쿼리입니다.
```sql
SELECT *
FROM departments d,
  (SELECT * FROM dept_emp de WHERE de.dept_no=d.dept_no) x
WHERE d.dept_no=x.dept_no LIMIT 10;
```
여기에서
`SELECT * FROM dept_emp de WHERE de.dept_no=d.dept_no` 부분이 상관 서브쿼리죠.
하지만 여기서 사용하는 d.dept_no은 외부 쿼리의 테이블의 데이터를 참조해야 하는데 여기서 참조하는 d라는 테이블도 상관서브쿼리가 있는 FROM절에 같이 걸려 있기 때문이라고 생각해요.

외부 쿼리 테이블의 데이터를 참조하기 위해선 데이터가 조회된 상태여야 하는데, FROM절에 같이 걸려 있으면 해당하는 상태가 아니기 때문에 불가능하다고 생각합니다.

(요건 공식 문서에 있는 것이라기보단 저으 언어입니다~)
